config/routes.rb
Rails.application.routes.draw do
  get 'teach_relationships/my_courses'
  get 'teach_relationships/submit_grades'
  get 'teach_relationships/notification'
  get 'forget_password/create'
  get 'forget_password/destroy'
  get 'email_activation/new'
  get 'email_activation/destroy'
  get 'email_activation/update'
  get 'password_reset/create'
  get 'password_reset/destroy'
  get 'password_reset/update'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'sessions#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :students, only: [:show, :update]
  resources :teachers, only: [:show, :update]
  resources :courses, only: [:index, :show]
  resources :email_activation, only: [:edit]
  resources :password_reset, only: [:edit]

  get '/select_courses', to: 'courses#select_courses'
  post '/select_courses', to: 'courses#select_courses'
  get '/selected_courses', to: 'courses#selected_courses'
  post '/selected_courses', to: 'courses#selected_courses'
  get '/credit_count', to: 'courses#credit_count'

  post '/to_select_course', to: 'select_relationships#create'
  delete '/to_un_select_course', to: 'select_relationships#destroy'
  post '/set_degree_course', to: 'select_relationships#update'
  get '/grades', to: 'select_relationships#grades'

  get '/my_courses', to: 'teach_relationships#my_courses'
  get '/submit_grades', to: 'teach_relationships#submit_grades'
  get '/notification', to: 'teach_relationships#notification'
  get '/students_of_course', to: 'teach_relationships#students_of_course'
  get '/update_grade', to: 'teach_relationships#update'
  post '/send_course_notification', to: 'teach_relationships#send_course_notification'

  get '/home', to: 'static_pages#home'
  get '/user_profile', to: 'static_pages#user_profile'
  get '/password_setting', to: 'static_pages#update_password'
  get '/email_setting', to: 'static_pages#email_setting'
  get '/forget_password', to: 'static_pages#forget_password'

  post '/update_password', to: 'password_reset#password_setting'
  post '/password_reset', to: 'password_reset#create'
  post '/to_password_reset', to: 'password_reset#update'

  post '/email_activation', to: 'email_activation#create'
end

app/views/shared/_bootstrap_table.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.2/bootstrap-table.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.2/bootstrap-table.min.js"></script>
<!-- Latest compiled and minified Locales -->
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.2/locale/bootstrap-table-zh-CN.min.js"></script>

<style>
  td {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
  }

  .table-operation-a:hover {
    background: black;
    color: white;
  }

</style>

app/views/shared/_sidebar.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<%= stylesheet_link_tag 'sidebar', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="nav-side-menu">
  <div class="brand"><a href="/home"><span class="sidebar-logo" >选 课 系 统</span></a></div>
  <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

  <div class="menu-list">

    <ul id="menu-content" class="menu-content collapse out">
      <% if option == 'student' %>
        <li data-toggle="collapse" data-target="#course-management" class="collapsed">
          <span style="margin-left: 22px">课 程 管 理</span>
        </li>
        <ul class="sub-menu collapse in" id="course-management">
          <li><%= link_to '选择课程', select_courses_url(page: 1) %></li>
          <li><%= link_to '已选课程', selected_courses_url %></li>
          <li><%= link_to '学分统计', credit_count_url %></li>
          <li><%= link_to '成绩查询', grades_url %></li>
        </ul>

      <% elsif option == 'teacher' %>

        <li data-toggle="collapse" data-target="#course-management" class="collapsed">
          <span style="margin-left: 22px">课 程 管 理</span>
        </li>
        <ul class="sub-menu collapse in" id="course-management">
          <li><%= link_to '查看课程', my_courses_url %></li>
          <li><%= link_to '成绩登记', submit_grades_url %></li>
          <li><%= link_to '发布通知', notification_url %></li>
        </ul>

    <% end %>
      <li data-toggle="collapse" data-target="#service" class="collapsed">
        <span style="margin-left: 22px">账 号 管 理</span>
      </li>
      <ul class="sub-menu collapse in" id="service">
        <li><%= link_to '个人资料', user_profile_url %></li>
        <li><%= link_to '邮箱设置', email_setting_url %></li>
        <li><%= link_to '修改密码', password_setting_url %></li>
      </ul>
      <li style="position: absolute; bottom: 0; width: 100%; text-align: center">
        <i class='fa fa-power-off fa-lg' style='margin-right: 10px'></i>
        <%= link_to "退 出 登 录", logout_path, method: :delete, class: 'logout-a' %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_user_info.html.erb
<%= form_for(@current_user, as: :student) do |f| %>

  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <h3>个人信息</h3>
      <div class="divide" style="margin-bottom: 20px"></div>
      <div class="row">
        <div class="col-md-6">
          <%= f.label :姓名 %>
          <p class="form-control-static"><%= print(@current_user.name) %></p>

          <% if option == 'student' %>
            <%= f.label :学号 %>
            <p class="form-control-static"><%= print(@current_user.sno) %></p>
          <% elsif option == 'teacher' %>
            <%= f.label :教职工号 %>
            <p class="form-control-static"><%= print(@current_user.tno) %></p>
          <% end %>

          <%= f.label :性别 %>
          <p class="form-control-static"><%= print(@current_user.gender) %></p>
        </div>
        <div class="col-md-6">
          <%= f.label :出生日期 %>
          <p class="form-control-static"><%= print(@current_user.birth_date.year) %>
            年<%= print(@current_user.birth_date.month) %>月<%= print(@current_user.birth_date.day) %>日</p>

          <%= f.label :电子邮箱 %>
          <p class="form-control-static"><%= print(@current_user.email) %></p>

          <%= f.label :联系方式 %>
          <p class="form-control-static"><%= print(@current_user.phone) %></p>
        </div>
      </div>
    </div>

    <div class="col-md-2">

    </div>

  </div>
  <div class="row">
    <div class="col-md-2">

    </div>

    <% if option == 'student' %>

      <div class="col-md-8">
        <h3>学籍信息</h3>
        <div class="divide" style="margin-bottom: 20px"></div>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :学历 %>
            <p class="form-control-static"><%= print(@current_user.degree) %></p>

            <%= f.label :专业 %>
            <p class="form-control-static"><%= print(@current_user.major) %></p>
          </div>
          <div class="col-md-6">
            <%= f.label :院系 %>
            <p class="form-control-static"><%= print(@current_user.department.name) %></p>
            <%= f.label :入学年月 %>
            <p class="form-control-static"><%= print(@current_user.enrolled_date.year) %>
              年<%= print(@current_user.enrolled_date.month) %>月</p>
          </div>
        </div>
      </div>

    <% elsif option == 'teacher' %>
      <div class="col-md-8">
        <h3>教籍信息</h3>
        <div class="divide" style="margin-bottom: 20px"></div>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :职称 %>
            <p class="form-control-static"><%= print(@current_user.title) %></p>
          </div>
          <div class="col-md-6">
            <%= f.label :院系 %>
            <p class="form-control-static"><%= print(@current_user.department.name) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-2">

  </div>

  </div>





<% end %>