config/routes.rb
Rails.application.routes.draw do
  get 'teach_relationships/my_courses'
  get 'teach_relationships/submit_grades'
  get 'teach_relationships/notification'
  get 'forget_password/create'
  get 'forget_password/destroy'
  get 'email_activation/new'
  get 'email_activation/destroy'
  get 'email_activation/update'
  get 'password_reset/create'
  get 'password_reset/destroy'
  get 'password_reset/update'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'sessions#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :students, only: [:show, :update]
  resources :teachers, only: [:show, :update]
  resources :courses, only: [:index, :show]
  resources :email_activation, only: [:edit]
  resources :password_reset, only: [:edit]

  get '/select_courses', to: 'courses#select_courses'
  post '/select_courses', to: 'courses#select_courses'
  get '/selected_courses', to: 'courses#selected_courses'
  post '/selected_courses', to: 'courses#selected_courses'
  get '/credit_count', to: 'courses#credit_count'

  post '/to_select_course', to: 'select_relationships#create'
  delete '/to_un_select_course', to: 'select_relationships#destroy'
  post '/set_degree_course', to: 'select_relationships#update'
  get '/grades', to: 'select_relationships#grades'

  get '/my_courses', to: 'teach_relationships#my_courses'
  get '/submit_grades', to: 'teach_relationships#submit_grades'
  get '/notification', to: 'teach_relationships#notification'
  get '/students_of_course', to: 'teach_relationships#students_of_course'
  get '/update_grade', to: 'teach_relationships#update'
  post '/send_course_notification', to: 'teach_relationships#send_course_notification'

  get '/home', to: 'static_pages#home'
  get '/user_profile', to: 'static_pages#user_profile'
  get '/password_setting', to: 'static_pages#update_password'
  get '/email_setting', to: 'static_pages#email_setting'
  get '/forget_password', to: 'static_pages#forget_password'

  post '/update_password', to: 'password_reset#password_setting'
  post '/password_reset', to: 'password_reset#create'
  post '/to_password_reset', to: 'password_reset#update'

  post '/email_activation', to: 'email_activation#create'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :is_logged_in?
  before_action :is_teacher?, only: [:my_courses,
                                     :submit_grades,
                                     :notification]
  before_action :is_student?, only: [:select_courses,
                                     :selected_courses,
                                     :get_select_courses,
                                     :get_selected_courses,
                                     :credit_count]

  def new
  end

  def create
  end

  def update
  end

  def show
    @courses = Course.find(params[:id])
  end

  def index
    @courses = Course.all
  end

  def select_courses
    @years = [2017, 2018, 2019, 2020]
    @semester = ["春季", "秋季", "夏季"]
    @course_types = ["专业必修课", "专业选修课", "专业核心课", "公共必修课", "公共选修课", "专业讨论课"]
    @page = params[:page]
    @query_params = Hash.new
    @departments = Department.all

    unless params[:department].nil? || params[:department] == "全部"
      @query_params.store :department_id, params[:department].to_i
    end
    unless params[:year].nil? || params[:year] == "全部"
      @query_params.store :year, params[:year]
    end
    unless params[:semester].nil? || params[:semester] == "全部"
      @query_params.store :semester, params[:semester]
    end
    unless params[:course_type].nil? || params[:course_type] == "全部"
      @query_params.store :course_type, params[:course_type]
    end

    p "Query params: " + @query_params.to_s

    @current_user = Student.find_by(sno: session[:no])
    @courses = Course.where(@query_params).paginate(page: @page)
  end

  def selected_courses
    @years = [2017, 2018, 2019, 2020]
    @semester = ["春季", "秋季", "夏季"]
    @course_types = ["专业必修课", "专业选修课", "专业核心课", "公共必修课", "公共选修课", "专业讨论课"]
    @page = params[:page]
    @query_params = Hash.new
    @departments = Department.all

    unless params[:department].nil? || params[:department] == "全部"
      @query_params.store :department_id, params[:department].to_i
    end
    unless params[:year].nil? || params[:year] == "全部"
      @query_params.store :year, params[:year]
    end
    unless params[:semester].nil? || params[:semester] == "全部"
      @query_params.store :semester, params[:semester]
    end
    unless params[:course_type].nil? || params[:course_type] == "全部"
      @query_params.store :course_type, params[:course_type]
    end

    @current_user = Student.find_by(sno: session[:no])
    @courses = @current_user.courses.where(@query_params).paginate(page: @page)
  end

  def credit_count
    @current_user = current_user
  end

  def my_courses
    @courses = @current_user.courses
  end

  def submit_grades

  end

  def notification

  end


end

app/helpers/courses_helper.rb
module CoursesHelper

  def get_teachers_name(course)
    if course.teachers.count != 1
      course.teachers.first.name + "等"
    else
      course.teachers.first.name
    end
  end

end

app/views/courses/_course_info.html.erb
<%= form_for(@course, as: :course) do |f| %>

  <%= f.label :课程编号 %>
  <p class="form-control-static"><%= print(@course.cno) %></p>

  <%= f.label :课程名 %>
  <p class="form-control-static"><%= print(@course.name) %></p>


<% end %>

app/views/courses/credit_count.html.erb
<% provide :title, ('当前用户：' + current_user.name if logged_in?) %>
<% provide :subtitle, ('学分统计') %>
<body style="background: none">

<%= render 'shared/sidebar' %>
<%= render 'shared/bootstrap_table' %>
<div class="right-side-div">

  <h1><%= yield :subtitle %></h1>
  <div class="divide"></div>
  <% flash.each do |message_type, message| %>
    <div class="alert course-alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <table class="table table-hover">
    <thead>
    <th>
      专业必修课
    </th>
    <th>
      专业选修课
    </th>
    <th>
      专业核心课
    </th>
    <th>
      公共必修课
    </th>
    <th>
      公共选修课
    </th>
    <th>
      专业讨论课
    </th>
    <th>
      总计学分
    </th>
    </thead>
    <tbody>
    <tr>
      <td><%= grade_count @current_user.courses.where(course_type: "专业必修课") %></td>
      <td><%= grade_count @current_user.courses.where(course_type: "专业选修课") %></td>
      <td><%= grade_count @current_user.courses.where(course_type: "专业核心课") %></td>
      <td><%= grade_count @current_user.courses.where(course_type: "公共必修课") %></td>
      <td><%= grade_count @current_user.courses.where(course_type: "公共选修课") %></td>
      <td><%= grade_count @current_user.courses.where(course_type: "专业讨论课") %></td>
      <td><%= grade_count @current_user.courses %></td>
    </tr>
    </tbody>
  </table>

</div>

<style>

  th {
    text-align: center;
  }

</style>

</body>

app/views/courses/destroy.html.erb
<h1>Courses#destroy</h1>
<p>Find me in app/views/courses/destroy.html.erb</p>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

app/views/courses/index.html.erb
<% provide :title, ('当前用户：' + current_user.name if logged_in?) %>
<% provide :subtitle, ('选择课程') %>
<body style="background: none">

<%= render 'shared/sidebar' %>
<%= render 'shared/bootstrap_table' %>

<div class="right-side-div">

  <% flash.each do |message_type, message| %>
    <div class="alert login-alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <h1><%= yield :subtitle %></h1>
  <div class="divide"></div>
  <table id="ArbetTable">

  </table>
</div>

<script type="application/javascript">
    $(function () {
        var oTable = new TableInit();
        oTable.Init();
    });

    var TableInit = function () {
        var oTableInit = {};
        oTableInit.Init = function () {
            $('#ArbetTable').bootstrapTable({
                url: '/all_courses',         //请求后台的URL（*）
                method: 'get',                      //请求方式（*）
                toolbar: '#toolbar',                //工具按钮用哪个容器
                striped: true,                      //是否显示行间隔色
                cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                pagination: true,                   //是否显示分页（*）
                sortable: true,                     //是否启用排序
                sortOrder: "asc",                   //排序方式
                queryParams: oTableInit.queryParams,//传递参数（*）
                sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
                pageNumber: 1,                       //初始化加载第一页，默认第一页
                pageSize: 10,                       //每页的记录行数（*）
                pageList: [10, 25, 50, 100],        //可供选择的每页的行数（*）
                contentType: "application/x-www-form-urlencoded",
                strictSearch: true,
                showColumns: true,                  //是否显示所有的列
                showRefresh: true,                  //是否显示刷新按钮
                minimumCountColumns: 2,             //最少允许的列数
                clickToSelect: true,                //是否启用点击选中行
                height: 700,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                showToggle: true,                    //是否显示详细视图和列表视图的切换按钮
                cardView: false,                    //是否显示详细视图
                detailView: false,                   //是否显示父子表
                columns: [
                    {
                        field: 'cno',
                        title: '课程号'
                    }, {
                        field: 'title',
                        title: '课程名'
                    }, {
                        field: 'year',
                        title: '学年'
                    }, {
                        field: 'semester',
                        title: '学期'
                    }, {
                        field: 'select_limit',
                        title: '限选人数',
                    }, {
                        field: 'selected_count',
                        title: '已选人数',
                    }, {
                        field: 'credit',
                        title: '学分',
                    }, {
                        field: 'hours',
                        title: '学时',
                    }, {
                        field: 'weeks',
                        title: '周次',
                    }, {
                        field: 'time_and_classroom',
                        title: '时间/教室',
                    }, {
                        field: 'dept_name',
                        title: '开课单位',
                    }, {
                        field: 'teachers',
                        title: '授课教师',
                    }, {
                        field: 'operate',
                        title: '操作',
                        formatter: operateFormatter //自定义方法，添加操作按钮
                    },
                ],
            });

        };

        //得到查询的参数
        oTableInit.queryParams = function (params) {
            var temp = {   //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
                limit: params.limit,   //页面大小
                offset: params.offset
            };
            return temp;
        };
        return oTableInit;
    };


    function operateFormatter(value, row, index) {//赋予的参数
        return [
            '<%= link_to "选课", to_select_course_path, method: :create,
                  data: { confirm: "确定要选择这门课吗?" } %>',
            '<a href="#" style="margin-left: 10px">详细信息</a>',
        ].join('');
    }

</script>

</body>

app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

app/views/courses/select_courses.html.erb
<% provide :title, ('当前用户：' + current_user.name if logged_in?) %>
<% provide :subtitle, ('选择课程') %>
<body style="background: none">

<%= render 'shared/sidebar' %>
<%= render 'shared/bootstrap_table' %>
<div class="right-side-div">

  <h1><%= yield :subtitle %></h1>
  <div class="divide"></div>
  <% flash.each do |message_type, message| %>
    <div class="alert course-alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <form class="form-inline" style="text-align: right; padding-right: 0" action="/select_courses" method="post">
    <%= tag(:input, :type => "hidden", :name =>
        request_forgery_protection_token.to_s, :value =>
                form_authenticity_token) %>

    <div class="form-group">
      <label for="year">学年：</label>
      <select class="form-control" id="year" name="year">
        <option>全部</option>
        <%= @years.each do |year| %>
          <% if params[:year].to_i == year %>
            <option value="<%= year %>" selected="selected"><%= year %></option>
          <% else %>
            <option value="<%= year %>"><%= year %></option>
          <% end %>
        <% end %> %>
      </select>
    </div>

    <div class="form-group">
      <label for="semester">学期：</label>
      <select class="form-control" id="semester" name="semester">
        <option>全部</option>
        <%= @semester.each do |value| %>
          <% if params[:semester].to_s == value %>
            <option value="<%= value %>" selected="selected"><%= value %></option>
          <% else %>
            <option value="<%= value %>"><%= value %></option>
          <% end %>
        <% end %> %>
      </select>
    </div>

    <div class="form-group">
      <label for="department">开课单位：</label>
      <select class="form-control" id="department" name="department">
        <option>全部</option>
        <% @departments.each do |d| %>
          <% if params[:department].to_i == d.id %>
            <option selected="selected" value="<%= d.id %>>"><%= d.name %></option>
          <% else %>
            <option value="<%= d.id %>"><%= d.name %></option>
          <% end %>
        <% end %>
      </select>
    </div>

    <div class="form-group">
      <label for="course-type">课程类型：</label>
      <select class="form-control" id="course-type" name="course_type">
        <option>全部</option>
        <%= @course_types.each do |value| %>
          <% if params[:course_type].to_s == value %>
            <option value="<%= value %>" selected="selected"><%= value %></option>
          <% else %>
            <option value="<%= value %>"><%= value %></option>
          <% end %>
        <% end %> %>
      </select>
    </div>

    <div class="form-group">
      <input type="submit" class="btn btn-default" value="搜 索"/>
    </div>

  </form>
  <table class="table table-striped table-bordered table-hover" style="margin-top: 10px">
    <thead>
    <th>课程编号</th>
    <th>课程名</th>
    <th>周次/时间/教室</th>
    <th>学时/学分</th>
    <th>类型</th>
    <th>开课单位</th>
    <th>授课教师</th>
    <th>限选/已选人数</th>
    <th>操作</th>
    </thead>
    <tbody>

    <% @courses.each do |c| %>
      <% if !c.students.include? @current_user %>
        <tr>
          <td><%= c.cno %></td>
          <td><%= c.title %></td>
          <td>
            <% c.week_time_classroom.split(";").each do |time| %>
              <div><%= time %></div>
            <% end %>
          </td>
          <td><%= c.hours.to_s + "/" + c.credit.to_s %></td>
          <td><%= c.course_type %></td>
          <td><%= c.department.name %></td>
          <td><%= get_teachers_name c %></td>
          <td><%= c.select_limit.to_s + "/" + c.students.count.to_s %></td>
          <td><%= link_to '选课', to_select_course_url(cno: c.cno), method: :post, data: {confirm: "您确定要选这门课吗？"} %></td>
        </tr>
      <% end %>
    <% end %>

    </tbody>
  </table>

  <%= will_paginate @courses, {previous_label: "« 上一页", next_label: "下一页 »"} %>
</div>

<style>

  th {
    text-align: center;
  }

  select {
    display: inline;
    width: auto;
    margin-right: 20px;
  }

  a:hover {
    background: none;
  }


</style>

</body>

app/views/courses/selected_courses.html.erb
<% provide :title, ('当前用户：' + current_user.name if logged_in?) %>
<% provide :subtitle, ('已选课程') %>
<body style="background: none">

<%= render 'shared/sidebar' %>
<%= render 'shared/bootstrap_table' %>
<div class="right-side-div">

  <h1><%= yield :subtitle %></h1>
  <div class="divide"></div>
  <% flash.each do |message_type, message| %>
    <div class="alert course-alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <form class="form-inline" style="text-align: right; padding-right: 0" action="/selected_courses" method="post">

    <%= tag(:input, :type => "hidden", :name =>
        request_forgery_protection_token.to_s, :value =>
                form_authenticity_token) %>

    <div class="form-group">
      <label for="year">学年：</label>
      <select class="form-control" id="year" name="year">
        <option>全部</option>
        <%= @years.each do |year| %>
          <% if params[:year].to_i == year %>
            <option value="<%= year %>" selected="selected"><%= year %></option>
          <% else %>
            <option value="<%= year %>"><%= year %></option>
          <% end %>
        <% end %> %>
      </select>
    </div>

    <div class="form-group">
      <label for="semester">学期：</label>
      <select class="form-control" id="semester" name="semester">
        <option>全部</option>
        <%= @semester.each do |value| %>
          <% if params[:semester].to_s == value %>
            <option value="<%= value %>" selected="selected"><%= value %></option>
          <% else %>
            <option value="<%= value %>"><%= value %></option>
          <% end %>
        <% end %> %>
      </select>
    </div>

    <div class="form-group">
      <label for="department">开课单位：</label>
      <select class="form-control" id="department" name="department">
        <option>全部</option>
        <% @departments.each do |d| %>
          <% if params[:department].to_i == d.id %>
            <option selected="selected" value="<%= d.id %>>"><%= d.name %></option>
          <% else %>
            <option value="<%= d.id %>"><%= d.name %></option>
          <% end %>
        <% end %>
      </select>
    </div>

    <div class="form-group">
      <label for="course-type">课程类型：</label>
      <select class="form-control" id="course-type" name="course_type">
        <option>全部</option>
        <%= @course_types.each do |value| %>
          <% if params[:course_type].to_s == value %>
            <option value="<%= value %>" selected="selected"><%= value %></option>
          <% else %>
            <option value="<%= value %>"><%= value %></option>
          <% end %>
        <% end %> %>
      </select>
    </div>

    <div class="form-group">
      <input type="submit" class="btn btn-default" value="搜 索"/>
    </div>

  </form>
  <table class="table table-striped table-bordered table-hover" style="margin-top: 10px">
    <thead>
    <th>课程编号</th>
    <th>课程名</th>
    <th>周次/时间/教室</th>
    <th>学时/学分</th>
    <th>类型</th>
    <th>开课单位</th>
    <th>授课教师</th>
    <th>限选/已选人数</th>
    <th>是否学位课</th>
    <th>操作</th>
    </thead>
    <tbody>

    <% @courses.each do |c| %>
      <tr>
        <td><%= c.cno %></td>
        <td><%= c.title %></td>
        <td>
          <% c.week_time_classroom.split(";").each do |time| %>
            <div><%= time %></div>
          <% end %>
        </td>
        <td><%= c.hours.to_s + "/" + c.credit.to_s %></td>
        <td><%= c.course_type %></td>
        <td><%= c.department.name %></td>
        <td><%= get_teachers_name c %></td>
        <td><%= c.select_limit.to_s + "/" + c.students.count.to_s %></td>
        <td>
          <% if is_degree_course(@current_user, c) %>
            是
          <% else %>
            否
          <% end %>
        </td>
        <td>
          <%= link_to '退课', to_un_select_course_url(cno: c.cno), method: :delete, data: {confirm: "您确定要退选这门课吗？"} %>
          <% unless is_degree_course(@current_user, c) %>
            <%= link_to '设为学位课', set_degree_course_url(cno: c.cno, option: 'set'), method: :post, data: {confirm: "您确定要将《" + c.title + "》设为学位课吗？"} %>
          <% else %>
            <%= link_to '取消学位课', set_degree_course_url(cno: c.cno, option: 'un_set'), method: :post, data: {confirm: "您确定要取消将《" + c.title + "》设为学位课吗？"} %>
          <% end %>
        </td>
      </tr>
    <% end %>

    </tbody>
  </table>

  <%= will_paginate @courses, {previous_label: "« 上一页", next_label: "下一页 »"} %>
</div>

<style>

  select {
    display: inline;
    width: auto;
    margin-right: 20px;
  }

  a:hover {
    background: none;
  }

</style>

</body>

app/views/courses/show.html.erb
<% provide :title, ('当前用户：' + current_user.name if logged_in?) %>
<% provide :subtitle, (current_time_type + '好，欢迎进入选课系统！') %>
<body style="background: none">

<%= render 'shared/sidebar' %>

<div class="right-side-div">

  <% flash.each do |message_type, message| %>
    <div class="alert login-alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <h1><%= yield :subtitle %></h1>
  <div class="divide"></div>
  <div class="row">
    <div class="col-md-12">
      <h2>课程详细信息</h2>
      <%= render :partial => 'course_info', :locals => {course: @course} %>
    </div>
    </div>
  </div>

</div>


</body>

app/views/courses/update.html.erb
<h1>Courses#update</h1>
<p>Find me in app/views/courses/update.html.erb</p>